# Generated by Django 4.0.6 on 2022-08-01 17:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipe_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='new-recipe', max_length=400),
        ),
    ]
