# Generated by Django 4.0.6 on 2022-08-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_image_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
