# Generated by Django 4.0.6 on 2022-08-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_ingredients_list_recipe_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_list',
            field=models.CharField(blank=True, default='[]', max_length=1000, null=True),
        ),
    ]
