# Generated by Django 4.0.6 on 2022-08-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_ingredients_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_list',
            field=models.JSONField(blank=True, default='[]', max_length=1000, null=True),
        ),
    ]
