# Generated by Django 4.0.6 on 2022-08-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_ingredients_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_list',
            field=models.JSONField(blank=True, default='{}', max_length=1000, null=True),
        ),
    ]
