# Generated by Django 4.0.6 on 2022-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_likes_alter_recipe_ingredients_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
